### ISSUE TITLE
Repository Over Data Quota for LFS

### ISSUE THREAD

**Issue by sergkhl** [FirebaseExtended/compass-ai-travel-planning-sample-flutter#11]
When running `git lfs pull`, the following error occurs:

```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/FirebaseExtended/compass-ai-travel-planning-sample-flutter.git'
```

### Steps to Reproduce:
1. Clone the repository: `git clone https://github.com/FirebaseExtended/compass-ai-travel-planning-sample-flutter.git`
2. Navigate to the cloned directory: `cd compass-ai-travel-planning-sample-flutter`
3. Run the command: `git lfs pull`

### Suggested Actions:
1. **Increase LFS Data Quota:** If its possible - purchase additional data packs to restore access, this might be easiest solution, but can become out of data again depending on how many people will try to run IDX environment.
2. **Split Large Files:** Consider splitting large files into smaller archives <100mb to avoid using LFS for them.
3. **Store Large Files Externally:** Move large files to external storage services that support automated downloading. Below are some options: 

### External Storage Options with Automated Downloads:

1. **Amazon S3:**
   - Use AWS CLI for automated downloads.
   - Example command: `aws s3 cp s3://bucket-name/file-path local-file-path`

2. **Google Cloud Storage:**
   - Use `gsutil` for automated downloads.
   - Example command: `gsutil cp gs://bucket-name/file-path local-file-path`

3. **Dropbox:**
   - Use the Dropbox API for automated downloads.
   - Example command with `curl`: `curl -L -o local-file-path "https://www.dropbox.com/s/FILE_ID/file-name?dl=1"`

**Comment by nohe427** [comment]
Thanks for brining this up. We migrated the storage to Firebase storage.
