### ISSUE TITLE
About API key setting practice

### ISSUE THREAD

**Issue by JaewooKim0** [FirebaseExtended/compass-ai-travel-planning-sample-flutter#12]
Is pasting the API key into env section of the .idx/dev.nix safe approach?

**Comment by nohe427** [comment]
@rodydavis - Can you take a look at this?

**Comment by rodydavis** [comment]
The best practice would be to have the variables defined with empty values in the dev.nix.

After you import your template/repo from GitHub you can set the values and will be secure in the VM.

You will need to make sure not to deploy the variables to source control by removing the defined values only when you need to make changes to the dev.nix (which should not happen often).

**Comment by nohe427** [comment]
If we did want to do long term storage in the dev.nix file, I imagine that is when secrets would come into play. Is there a feature request for that? Where would I log one if I wanted that?

**Comment by rodydavis** [comment]
That is a great point!

You can definitely submit a feature request here:
https://community.idx.dev/

**Comment by nohe427** [comment]
@JaewooKim0 I hope that answers your question. I am going to close this issue. If you feel it is not resolved, please let me know and I can reopen it.
